김진호 타이머 미션 제출합니다.
TeamCrazyPerformance/front-todolist pull request #2
Opened 2023-01-25 07:32 UTC by wlsh44

타이머 미션 제출합니다!
우선 처음에 함께 진행을 하다가 중간까지는 따로 진행해서 죄송합니다..!
이번에 느낀 점은 css에 대한 거부감이 좀 줄어든 것 같아서 좋았습니다. 🙂
그리고 페어프로그래밍을 할 때 기본적으로 필요한 전제조건에 생각해보는 시간이었습니다!

### 힘들었던 점

- 페어프로그래밍

### 궁금한 점

css로 `display: none` 을 설정을 했는데 js에서 `Element.style.display` 를 찍으면 `''`가 결과로 나오는데 왜 그런걸까요..? 개발자 도구에서 확인을 할 때는 잘 적용이 되어있었고, html의 style에 직접 넣고 출력하면 `none`으로 잘 출력이 되어서 궁금했습니다.

2023-01-26 14:10 UTC, usageness requested changes
안녕하세요, 진호님!
이번에도 미션을 멋지게 수행해주셨네요.
css에 거부감이 줄어드셨다니 제가 다 기쁩니다 😉

페어 프로그래밍은 어떠셨나요?
어떻게 해야할지 느끼신 바가 있다니 정말 궁금하네요 ㅎㅎ
다음에 한 번 공유해주시면 좋겠어요! 

html, css, javascript 가 섞여있는 어지러운 환경에서도
잘 설계된 프로그래밍을 하는 것이 중요하다는 점,
다음 미션에서 확실히 느끼실 수 있을거에요!

구현하시느라 고생 많으셨고, 간단한 수정사항만 반영해주시면
바로 approve 드리도록 하겠습니다!

아래는 질문에 대한 답변입니다 🙋‍♂️

> css로 display: none 을 설정을 했는데 js에서 Element.style.display 를 찍으면 ''가 결과로 나오는데 왜 그런걸까요..? 개발자 도구에서 확인을 할 때는 잘 적용이 되어있었고, html의 style에 직접 넣고 출력하면 none으로 잘 출력이 되어서 궁금했습니다.

JS에서 `element.style` 로 불러오는 값은 html의 문서에 표기된 값입니다.
inline-style이라고 부르는 방식처럼 문서에 직접적으로 표시된 값이 아니라면
실제로 적용된 스타일이라고 해도 불러와지지 않습니다.

```html
<div style="display: block;"></div>
```

개발자 도구에서 element에 적용하는 스타일 또한 인라인으로 추가되기 때문에
정상적으로 작동하는걸 확인하셨을거에요!

![image](https://user-images.githubusercontent.com/28296575/214854789-93a64ccc-6b11-4c52-bf34-dad1f20b5a8f.png)

2023-01-26 14:10 UTC, usageness commented on todolist_func.js
> +let todoNum = 0;
`todoNum` 을 전역 변수로 둔다는건, 자바스크립트에선 할 일의 개수만 관리하겠다는 의미와 같겠네요.
그렇다면 할 일에 대한 세부적인 내용은 html에 위임하려는 의도였다고 보아도 될까요?

2023-01-26 14:10 UTC, usageness commented on todolist_func.js
> +    clearTodoContent(todoContentElement);
할 일을 추가하면 입력창이 비워지는 동작은 사용자 입장에서는 당연하게 생각할만한 동작이죠.
하지만 개발자는 일일히 구현해줘야 하는... ㅠㅠ 
사용성을 고려한 좋은 코드라고 생각합니다!

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    position: sticky;
`position: sticky` 를 사용한 이유가 무엇일까요?
어떤 동작을 기대하고 사용하셨나요?

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    margin: 0;
`reset.css` 에 대해서 알아볼까요?

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    flex-direction: row;
`flex-direction` 속성의 기본값은 `row` 입니다!
굳이 적어주실 필요없어요~

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    margin-right: 2%;
축약형으로 쓰면 이렇게도 가능해요~
`margin: 0 2%;`

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    cursor: pointer;
`cursor: pointer` 는 모든 버튼에 다 필요한 속성인것 같은데, 
button에 기본 스타일로 지정해주는건 어떨까요?

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    flex: 1;
wow!!! flex의 축약형!

2023-01-26 14:10 UTC, usageness commented on todolist_style.css
> +    border-width: 0px 0px 1px 0px;
`0px` vs `0`

2023-01-28 03:27 UTC, wlsh44 reviewed
사실 이번에 진행할 때 js 리팩터링 정도만 하고 코드에는 최대한 손을 대지 않았습니다.
대신 '이건 이렇게 바꾸면 어떨까?', '이런 기능을 추가하면 어떨까?' 정도의 가이드나, 패어분들의 코드에 근거가 있으면 좋겠다는 생각에 '이건 왜 이렇게 했어?'라는 질문을 주면서 진행을 했는데, 그러다보니 진행이 많이 느려졌었습니다. 특히 3명이서 하다보니 많이 어수선한 분위기가 되었네요..

그래서 css의 디테일이나 네이밍의 통일성 (`todo` 와 `schedule`이 같은 의미로 쓰였던 점) 등 사소한 부분에 신경을 쓰지 못한 코드가 되어서 아쉬웠습니다.

다음 PR은 피드백 주신 것들이랑 이 부분에 대해 수정을 해서 올리도록 하겠습니다!

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    position: sticky;
`sticky` 는 `static` 과 `fixed`의 두 가지 특성을 갖고 있다는 글을 봤었습니다.
그래서 헤더를 `sticky`로 만들면 굳이 `fixed` 를 사용하기 위해 `margin` 을 따로 넣어주지 않아도 되어서 편리하다는 점에서 사용했습니다!

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    flex-direction: row;
수정하겠습니다!

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    cursor: pointer;
수정하겠습니다~

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    flex: 1;
flex를 자세하게 공부해볼까 했는데 너무 어렵고 외울게 많아서 포기..😂

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    border-width: 0px 0px 1px 0px;
`0px`이 2바이트 더 차지한다는 차이 외에는 딱히 없는 것 같네요 🤔

2023-01-28 03:27 UTC, wlsh44 commented on todolist_style.css
> +    margin: 0;
브라우저마다 기본으로 적용되는 css가 있다는걸 처음 알았습니다..!
한번 적용해볼게요 🙂

2023-01-28 03:27 UTC, wlsh44 commented on todolist_func.js
> +let todoNum = 0;
이 부분은 @eagleda 님의 코드를 베이스로 한 코드고, 할 일 삭제하는 함수 파라미터로 `this` 를 넣은 것으로 보아 그렇게 판단한 것 같습니다.
개인적으로는 todo 객체를 담는 배열을 따로 만들어서 구현을 하고싶었는데, 도저히 그럴 시간이 안날 것 같아서 제가 따로 진행했던 로컬 코드에만 묻어두었어요..😭

2023-01-31 08:15 UTC, usageness commented on todolist_func.js
> +let todoNum = 0;
다음 2차 요구사항에서 로컬 코드로 바꿔보실 기회가 있을거에요 :)

2023-01-31 08:24 UTC, usageness commented on todolist_style.css
> +    position: sticky;
오잉.. fixed를 사용했을때 `margin`이 필요하셨나요?
margin 이 필요했던 이유는 잘 모르겠지만, 두 포지션의 특징과 사용처를 간단히 보면

`sticky`는 페이지의 특정 위치에 자리하되, 스크롤이 되면 딸려서 이동합니다.
다만 움직일 수 있는 뷰포트의 범위를 설정할 수 있다는 특징이 있어 사이드바에 많이 사용합니다.

`fixed`의 경우 스크롤과 관계 없이 뷰포트의 특정 위치에 고정시킬 수 있다는 특징이 있어
항상 노출되어야 하는 사이드 메뉴나 헤더등에 많이 사용합니다.

2023-01-31 08:29 UTC, usageness approved these changes
미션 수행하시느라 고생하셨습니다!

리뷰로 남긴 내용들 반영해주신것 모두 확인했고,
다음 미션 발표까지 이번에 공부한 내용들을
다시 한 번 정리하는 시간을 가져보시면 좋을것 같습니다!

다음 미션 발표는 2월 2일 목요일입니다!
고생하셨어요 😄

2023-01-31 08:29 UTC, usageness approved these changes
미션 수행하시느라 고생하셨습니다!

리뷰로 남긴 내용들 반영해주신것 모두 확인했고,
다음 미션 발표까지 이번에 공부한 내용들을
다시 한 번 정리하는 시간을 가져보시면 좋을것 같습니다!

다음 미션 발표는 2월 2일 목요일입니다!
고생하셨어요 😄

2023-01-31 08:30 UTC, merged