이다용 투두리스트 미션 제출합니다.
TeamCrazyPerformance/front-todolist pull request #3
Opened 2023-01-25 07:35 UTC by eagleda

2023-01-27 09:47 UTC, usageness requested changes
안녕하세요, 다용님!
이번에도 디테일을 잘 살려주셔서 흐뭇했던 미션이네요 ㅎㅎ
어색하셨을텐데 페어 프로그래밍도 잘 해주셔서 뿌듯합니다.

다음 미션에서는 지금보다 요구사항도 추가되고 조금 더 복잡해질텐데,
지금 구조에서도 새로운 요구사항이나 수정사항을
충분히 수용할 수 있는지 한 번 생각해보시면 좋을 것 같아요!

늦은 시간까지 구현하시느라 정말 고생 많으셨고,
따로 남겨주신 질문은 없으시니 코멘트로 대신하겠습니다!
코멘트 확인하시고 살짝 다듬어서 다시 PR 날려주세요 :)

2023-01-27 09:47 UTC, usageness commented on todolist_func.js
> +let todoNum = 0;
`todoNum`을 직접 관리하셨군요!
당장에 나쁜 선택은 아니지만, 과연 동작이 많아지는 다음 미션에서는 어떨지..?

2023-01-27 09:47 UTC, usageness commented on todolist_func.js
> +            <button class='delete-button' onclick='removeSchedule(this)'>x</button>`;
템플릿을 만들어주셨네요 😄
좋은 방법이라고 생각해요~

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +}
전체적인 스타일을 초기화해준것 좋아요~
html과 body 모두에 flex가 들어가는건 살짝 아리송..? 했지만요!

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +    right: 0;
position을 sticky로 잡아주면 어떤 일이 일어나나요?
`position: fixed`와는 어떤 점이 다를까요?

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +    flex-direction: row;
flex-direction의 row는 굳이 적어주실 필요는 없습니다! 
기본이 row가 아닐때 초기화 용도로만 사용하시면 되어요~

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +    margin-right: 2%;
한 줄로 줄이면 `margin: 0 2%`  !

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +}
스타일이 겹치는 부분이 많은 것 같아요~
어떻게하면 줄여볼 수 있을까요?
(생각만 해보시면 됩니다!)

2023-01-27 09:47 UTC, usageness commented on todolist_style.css
> +    margin-right: 5px;
여기도 마찬가지로 축약형을 사용하면 한 줄로 줄일 수 있겠죠?

2023-01-31 09:59 UTC, eagleda commented
23.01.31 
코멘트하신 걸 보고 `todoNum`을 사용한 제어 방법 대신 `document`에 `todo`클래스의 div가 존재하는지 여부에 따라 동작하는 방식으로 변경하고,  margin을 축약형으로 변경, 불필요한 `.container`의 `flex-direction: row` 설정을 제거하였습니다.

추가적으로 추가,취소 버튼을 예시에 맞게 음영이 나타나지 않도록 변경했습니다.
(커밋을 style이라고 했는데 이 경우는 refactor나, design 타입이 더 정확한 표현이 맞겠죠..? 아직 커밋 메시지 분류가 어렵네요..)

2023-01-31 14:36 UTC, usageness approved these changes
안녕하세요, 다용님!
이번 리뷰 반영도 잘 해주셨네요. 고생 많으셨습니다!

> (커밋을 style이라고 했는데 이 경우는 refactor나, design 타입이 더 정확한 표현이 맞겠죠..? 아직 커밋 메시지 분류가 어렵네요..)

잘 하셨습니다. 의미만 제대로 전달될 수 있으면 좋은 이름이에요.
실제로 프론트에서 css 수정에는 style 접두어를 많이 사용합니다 :)

todo에 대한 데이터를 dom 한 곳에서 관리한다는 접근 방법도 훌륭했어요.
여러곳에서 나누어 관리하는것 자체가 위험하기 때문에,
javascript나 html 둘 중 한 곳에서만 관리하는게 좋다고 생각합니다.

고생 많으셨고, 2월 2일 이후에 다음 요구사항이 전달되기까지
지금까지의 리뷰를 다시 정리해보시길 추천합니다.

2023-01-31 14:36 UTC, usageness commented on todolist_func.js
> +    return (document.querySelector('.todo') == null);
동등 비교는 `==` 대신 `===` 로 사용해봅시다!

2023-01-31 14:36 UTC, merged