김경준 todolist 제출합니다.
TeamCrazyPerformance/front-todolist pull request #5
Opened 2023-01-25 13:28 UTC by AzureSoda

진행하면서 처음에는 계획을 세워서 진행했는데 진행할수록 뭔가 잘 안맞아 떨어져서 진행하기가 어려웠습니다. 페어프로그래밍을 하면서 요소가 나오는 지점이나 var, let에 대해서 다시금 공부할 수 있었습니다.

2023-01-28 08:45 UTC, usageness requested changes
안녕하세요, 경준님!
이번 미션도 수고 많으셨습니다.

우선 실행시켜봤는데, `+` 버튼이 안보이네요? 
누락된 파일이 있는것 같은데 확인 부탁드려요~
![image](https://user-images.githubusercontent.com/28296575/215254137-e04e5381-9369-4199-9894-f2b9e60c0534.png)

진행할수록 뭔가 잘 안맞아떨어진다면, 어떤 부분이 특히 그랬는지,
다음에 할땐 어떻게 해야 그런 문제를 막을 수 있을지 등을 정리해서 회고하는 시간을 가져보시길 추천해요.
끝날때까지 페어 프로그래밍은 계속 될 예정입니다 ㅋㅋ

저번에도 강조 드렸었지만, 쓸데없는 파일들은 `.gitignore` 파일에 명시해서 빼주시는게 좋아요.
레포지토리는 항상 깨끗하게 관리하는게 팀원들은 물론, 본인에게도 큰 도움이 됩니다.
추가로 `package-lock.json` 파일이 있던데... 어떤 경로로 올라가게 된건지...?
올리신 김에 `package.json` 의 역할에 대해서도 찾아보시면 좋겠어요~

기타 자세한 사항은 아래 코멘트를 참고해주시고,
반영이 끝나시면 다시 re-request review 부탁드려요!
고생하셨습니다!

2023-01-28 08:45 UTC, usageness commented on .vscode/launch.json
> +}
ide 파일은 빼주세요~~~~ 
꼭~~~~

2023-01-28 08:45 UTC, usageness commented on index.html
> +            <img id="plus-button" src="image\plusbutton.png" onclick="toggleCreateTodoForm()">
이미지 실종사건 😈😈😈

2023-01-28 08:45 UTC, usageness commented on index.html
> +                    <input type='button' class="add-cancel-btn" value="취소" onclick='toggleCreateTodoForm()'>
`<input type='button'>` vs `<button>`

둘은 어떤 차이가 있을까요?

2023-01-28 08:45 UTC, usageness commented on todolist_func.js
> +    }
아래쪽에 return을 이용한 스타일과 여기 else를 통한 스타일이 혼재되어 있어보이네요.
한 가지 방법으로 통일해볼까요?

2023-01-28 08:45 UTC, usageness commented on todolist_func.js
> +            <button class='delete-button' onclick='removeSchedule(this)'>x</button>`;
좋은 템플릿입니다!

2023-01-28 08:45 UTC, usageness commented on todolist_func.js
> +        todoContentElement.value = '';
꼼꼼한 후처리 좋아요~

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    position: sticky;
position: sticky 를 쓰신 이유가 궁금합니다!
sticky는 어떨때 쓰면 좋을까요?

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +}
브라우저의 기본 css와 reset.css 에 대해서도 한 번 알아봅시다!

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    right: 0;
여기 top과 left, right 속성은 왜 0으로 주게 되었나요?
이 속성들이 없으면 어떻게 될까요?

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    flex-direction: row;
flex-direction의 기본값은 row 이기 때문에 굳이 적어줄 필요가 없습니다~

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    margin-right: 2%;
축약형을 이용해서 `margin: 0 2%` 로도 쓸 수 있습니다!

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    flex: 1;
`flex: 1` 을 주게되면 어떤 속성들이 들어가게 되는건가요?

2023-01-28 08:45 UTC, usageness commented on todolist_style.css
> +    cursor: pointer;
👍

2023-02-01 08:54 UTC, AzureSoda commented
겨울방학 웹 스터디- todo list 1차 피드백
▶package-lock.json: 해당 프로젝트에서 사용하는 외부 패키지 의존성을 관리함
package-lock.json 파일은 npm을 사용해서 node_modules 트리나 package.json 파일을 수정하게 되면 자동으로 생성되는 파일입니다.
이 파일은 파일이 생성되는 시점의 의존성 트리에 대한 정확한 정보를 가지고 있습니다

▶ <input type='button'> vs <button>의 차이
button 태그와 input 태그의 가장 큰 차이점은 button은 스스로 닫지 않는 태그이고 input은 스스로 닫는 태그다.
따라서 button은 하위 태그들을 추가할 수 있습니다. input은 그럴 수가 없다.
Button에 하위요소를 추가할 수 있어서 디자인적 측면에서 더 자유롭다.
Button 태그는 속성값으로 폼을 제출하는 submit, 폼 안의 내용을 초기화 하는 reset, button은 그 자체로 사용되지 않고 click과 같이 써서 js와 같이 사용한다.
input태그를 사용하면 img태그를 사용할 수 없고 css의 background-image를 사용해야한다
button태그: 클릭 가능한 버튼을 생성, content를 포함
input태그: 텍스트 필드, 라디오 버튼, 체크박스등 다양한 입력요소를 생성할 수 있습니다. 타입속성에 따라 선택한 입력 요소에 따라 선택한 입력요소의 형태가 달라진다.

▶position: sticky
position: sticky 속성을 적용한 박스는 평소에 문서 안에서 position: static 상태와 같이 일반적인 흐름에 따르지만 스크롤 위치가 임계점에 이르면 position: fixed와 같이 박스를 화면에 고정할 수 있는 속성
요구사항에 따르면 헤더부분이 위에 고정되어 있어야 하기 때문에 position: sticky를 사용하게 되었습니다.

▶브라우저의 기본 css와 reset.css
각 브라우저마다 제공하는 기본 스타일이 다르다.
Reset css란, 브라우저 간의 요소들 차이를 없애 디폴트 값으로 초기화시키는 코드다.
HTML 요소에 내장된 고유 CSS 스타일 속성을 초기화 시켜서, 크로스브라우징 (= 브라우저마다 동일한 모양) 구현할 때 유용.

결론적으로 브라우저마다 기본으로 제공하는 스타일이 있어서 기본값을 주기 위해 설정을 해주는 세팅이다.

▶ sticky에 top과 left, right 속성은 왜 0으로 주게 되었나요?
sticky 속성은 top, bottom, left, right들 중에 하나를 필수적으로 설정해주어야 합니다. sitcky로 설정된 영역은 설정된 위치(예 top: 0px)에 도달하기 전까지는 static 속성처럼 행동하다가 설정된 위치에 다다르면 fixed 속성처럼 행동하는 속성이다.
어느 부분까지 sticky를 해줘야하는지 지정해 줘야한다

▶sticky 에 left 0 , right 0 을 하면 가로 스크롤을 감지할 때 씀

▶position: absolute에서 top과 left, right 속성은 왜 0으로 지정하는 이유
position: absolute 로 설정을 해놓았더라도 top 이나 left 와 같은 위치 값을 지정하지 않으면 position: static 과 마찬가지로 동작한다.

▶flex: 1
flex: 1은 
flex-grow: 1;
flex-shrink: 1;
flex-basis: 0%  과 같다.

2023-02-01 11:55 UTC, usageness commented
@AzureSoda 

# PR 상태 건드리지 마세요

`Close and comment`, `merge pull request` 절대 클릭 금지

2023-02-01 12:29 UTC, usageness approved these changes
안녕하세요 경준님!
정리 해주신 코멘트 잘 봤습니다.

모르는 내용을 찾아보고 공부하는건 당연히 필요합니다. 저도 매일 하고 있고...
정리하는건 좋은데 그걸 코드에 녹여내는 연습은 언제든 필요할 것 같습니다.
코드를 짤때도, 구글링을 할때도 항상 내가 뭘 하려고 하는건지에 대해서
먼저 생각한 다음에 실행하는게 효율 면에서도 좋구요.

단순히 기술이 아니라 기술을 통해서 해결하려는 문제에 집중하셨으면 좋겠습니다.
시간 관계상 여기서 머지하고, 다음 미션 진행하시면 되겠습니다.
고생하셨습니다 :)

2023-02-01 12:29 UTC, usageness commented on index.html
> +                    <input type='button' class="add-cancel-btn" value="취소" id="cancelbutton" onclick='toggleCreateTodoForm()'>
id 값을 추가한 의도가 무엇인가요?

2023-02-01 12:29 UTC, usageness commented on todolist_style.css
>  }
둘은 그냥 같은 코드 아닌가요?

2023-02-01 12:34 UTC, merged