김신영 투두리스트 미션 제출합니다.
TeamCrazyPerformance/front-todolist pull request #6
Opened 2023-01-25 13:30 UTC by ShinYoung-Kim

[구현]
-일정 추가/삭제
: 스케줄 배열을 만들어 관리 

-+ -> 일정 추가 영역 show
-추가/취소 버튼 -> 일정 추가 영역 hide
: show/hideContents 함수에 해당 상수화된 content 이름을 매개변수로 넣어 해당 content일 때 content의 style 변경

-일정 없으면 "남은 일정이 없어요"
: changeContainerStyle 함수를 만들어 배열에 스케줄이 있을 때/없을 때를 기준으로 container style 변경 + show/hide content

[질문]
-스크롤 자동 활성화
❓ 별도의 코드 없이 스크롤이 자동으로 생겼습니다. 이유가 뭔지 모르겠습니다.

-btnPlus
![image](https://user-images.githubusercontent.com/83866983/214574348-4a3193c3-b588-4aa7-944c-454f399ab536.png)
: btnPlus에서 display flex와 align 속성을 적용하지 않으면 위 사진처럼 버튼 텍스트가 버튼 테두리를 한참 벗어나게 생깁니다. 왜 이런 문제가 생길까요? +) 버튼 테두리가 두 가지 색이 섞여서 나타나는 이유는 뭔가요?

[help wanted]
-스크롤
: 스크롤이 자동으로 생기면 우측에 세로 스크롤만큼의 영역을 잡아먹게 되면서 가로 스크롤까지 생겼습니다. -> 가로 스크롤을 hide하여 가려둔 상태인데, 이 방법 말고 스크롤이 생기면 스크롤만큼의 영역을 뺀 부분을 전체 영역으로 인식하도록 할 수는 없을까요?

-js에서 style 변경
❓ js file에서 style을 변경하는 코드를 추가하면 ex. addScheduleContainer.style.display = 'block';
![image](https://user-images.githubusercontent.com/83866983/214571480-5da28620-6a61-43f3-a128-b8391b70a5ed.png)
사진처럼 html에 inline으로 style 코드가 추가됩니다. css file에서 변경되게 하는 방법은 없을까요?

-flex align
: 처음 container의 flex style은 남은 일정이 없어요 라는 메시지를 중앙배열하기 위해 
`container.style.flexDirection = "row"
        container.style.alignItems = "center";
        container.style.justifyContent = "center";` 
상태로 설정하였고, 스케줄이 추가되면 
`container.style.flexDirection = "column"
        container.style.alignItems = "flex-start";
        container.style.justifyContent = "flex-start";`
로 style이 바뀌도록 설정하였습니다. -> 이렇게 제어하는 것이 번거롭게 느껴져서 다른 방법은 없을지 질문드리고 싶습니다.

-flex 중복 사용
: body의 남은 부분을 container의 영역으로 주기 위해 body의 display를 flex로 사용하고, 이를 통해 제어되는 element 중 하나가 container가 되도록 설정하였습니다. 또 container에서 메시지를 중앙 정렬하거나 스케줄을 start로 정렬시키기 위해서 container의 display를 flex로 지정하게 되었습니다. 이처럼 flex를 중복사용해도 되나요? 아니면 전체적인 element 하나에(ex. body) display를 flex로 지정하고 그 안에 들어있는 element들을 각기 다른 방법으로 정렬시키는 방법을 사용할 수 있나요?

2023-01-28 17:51 UTC, usageness requested changes
안녕하세요, 신영님!
요구사항에 없던 기능도 꼼꼼하게 구현하고 처리해주신 부분이 인상깊었습니다!
정말 고생 많으셨어요 👍👍

이번엔 리뷰할 내용도 많았고, 정말 알찼네요. 하는 내내 정말 재밌었습니다.
자세한 리뷰 내용은 코멘트로 대신할게요.
코멘트 반영이 완료되시면 `re-request review` 부탁드립니다!

아래는 질문에 대한 답변입니다.

[질문]
> -스크롤 자동 활성화
❓ 별도의 코드 없이 스크롤이 자동으로 생겼습니다. 이유가 뭔지 모르겠습니다.

html 요소의 내부 요소 크기가 정해진 크기 값이나 뷰포트를 넘어가는 경우
스크롤은 자동으로 생성됩니다. 기본 동작이에요!

내용이 넘쳐서 한 번에 다 확인할 수 없으니,
사용자는 스크롤로 확인할 수 있도록 동작하길 기대할거에요.
사용자의 기대에 자연스럽게 따라가는 시스템이라고 생각하시면 되겠습니다!

> -btnPlus
: btnPlus에서 display flex와 align 속성을 적용하지 않으면 위 사진처럼 버튼 텍스트가 버튼 테두리를 한참 벗어나게 생깁니다. 왜 이런 문제가 생길까요? +) 버튼 테두리가 두 가지 색이 섞여서 나타나는 이유는 뭔가요?

![image](https://user-images.githubusercontent.com/28296575/215279993-f76e26de-f22f-4735-9699-1dc513b9e223.png)

1. 단순히 `font-size`가 부모의 크기를 넘어가서 그렇습니다~

2. `<button>` 태그에 기본으로 적용된 스타일이 나타나고 있어서 그렇습니다.
`border-style: outset` 이 적용되면 사진의 왼쪽처럼 (우, 하향)에 음영이 생기고
`border-style: inset` 이 적용되면 사진의 오른쪽처럼 (좌, 상향)에 음영이 생깁니다.

![image](https://user-images.githubusercontent.com/28296575/215281780-edeb1743-0833-4b5f-8c24-da03ee10d476.png)


[help wanted]
> -스크롤
: 스크롤이 자동으로 생기면 우측에 세로 스크롤만큼의 영역을 잡아먹게 되면서 가로 스크롤까지 생겼습니다. -> 가로 스크롤을 hide하여 가려둔 상태인데, 이 방법 말고 스크롤이 생기면 스크롤만큼의 영역을 뺀 부분을 전체 영역으로 인식하도록 할 수는 없을까요?

스크롤... 브라우저에 직접 적용된 부분이라 수정하기가 참 어렵죠 ㅠㅠ
저도 신영님이 하신 것처럼 `overflow-x: hidden` 으로 처리해주는 편입니다.
특정 요소에 height를 고정시켜 필요한 부분에만 스크롤이 적용되도록 할 수는 있습니다.

![image](https://user-images.githubusercontent.com/28296575/215282187-517c0bf3-f6c7-416d-a91f-99ec65c1c571.png)


> -js에서 style 변경
❓ js file에서 style을 변경하는 코드를 추가하면 ex. addScheduleContainer.style.display = 'block';
사진처럼 html에 inline으로 style 코드가 추가됩니다. css file에서 변경되게 하는 방법은 없을까요?


불가능합니다.
대신 변경하고 싶은 스타일이 있는 클래스를 선언하고,
해당 클래스를 붙여주는 방식을 추천합니다!



> -flex align
: 처음 container의 flex style은 남은 일정이 없어요 라는 메시지를 중앙배열하기 위해
container.style.flexDirection = "row" container.style.alignItems = "center"; container.style.justifyContent = "center";
상태로 설정하였고, 스케줄이 추가되면
container.style.flexDirection = "column" container.style.alignItems = "flex-start"; container.style.justifyContent = "flex-start";
로 style이 바뀌도록 설정하였습니다. -> 이렇게 제어하는 것이 번거롭게 느껴져서 다른 방법은 없을지 질문드리고 싶습니다.

남은 일정이 없다는 메시지가 있는 요소를 먼저 만들어 두고,
실제로 일정이 없을때는 해당 요소를 보여주시고, 일정이 생기면
일정 컨테이너를 보여주시면 될 것 같습니다!

`scheduleContainer` <-> `noScheduleContainer`
두 가지를 돌아가면서 보여주시면 되지 않을까요?

> -flex 중복 사용
: body의 남은 부분을 container의 영역으로 주기 위해 body의 display를 flex로 사용하고, 이를 통해 제어되는 element 중 하나가 container가 되도록 설정하였습니다. 또 container에서 메시지를 중앙 정렬하거나 스케줄을 start로 정렬시키기 위해서 container의 display를 flex로 지정하게 되었습니다. 이처럼 flex를 중복사용해도 되나요? 아니면 전체적인 element 하나에(ex. body) display를 flex로 지정하고 그 안에 들어있는 element들을 각기 다른 방법으로 정렬시키는 방법을 사용할 수 있나요?

먼저 flex를 중복해서 (말씀하신 내용대로라면 부모-자식간에 중첩해서) 사용하는건
오히려 제가 권장하고 싶은 패턴입니다!
`<div display: flex> 내부에 <div display: flex> 내부에 <div display: flex> 내부에 ...`
요소가 쌓여가는 과정을 생각해보면 알아서 정렬되기 때문에
이쪽이 훨씬 관리하기도 편리하니까요.

배치하고 싶은 요소의 특성에 따라서 다양하게 display 속성을 주시는것도 필요하고,
경우에 따라서는 position: absolute 나 position: fixed 같은 속성도 사용해주면 좋아요.
중복된다고 해서 망설이지 말고, 필요하다면 과감히 사용해주시면 되겠습니다.

다만 float을 이용한 방법은 권장하지 않고 있습니다.
다른 요소와의 관계를 무시하는 블럭이 따로 생성 되어버리기 때문에...

2023-01-28 17:51 UTC, usageness commented on script.js
> +const NO_SCHEDULE_MESSAGE = 2;
아래쪽에 switch문에서 사용하시려고 상수화 해주셨군요!
명시적으로 상황이 그려져서 좋은 상수화라고 생각해요.
다만 switch의 case가 반드시 number형만 받지는 않기 때문에
정수값을 줄 필요는 없긴 합니다! 그대로 문자열로 쓰셔도 좋아요~

2023-01-28 17:51 UTC, usageness commented on script.js
> +const schedulesContainer = document.getElementById("schedulesContainer");
👍👍👍👍👏👏👏 

마지막에 `schedulesContainer` 는 사용되지 않고있어요!

2023-01-28 17:51 UTC, usageness commented on script.js
> +let scheduleArray = [];
배열로 관리해주셨군요! 좋은 방법이에요!
다만 배열 내부의 값만 변하고, 배열 자체는 변하지 않으니
const로 선언해주어도 괜찮겠네요 :)

2023-01-28 17:51 UTC, usageness commented on script.js
> +}
인자로 들어오는 값에 맞는 target을 switch 문을 통해 지정해주셨네요!
이렇게 되면 요소가 많아질수록 `hideContents` 함수의 길이가 길어진다는 단점이 있을 것 같아요~
현재 구조같은 경우라면, 따로 함수를 만들지 않고 직접 변경해주셔도 괜찮을 것 같습니다!

2023-01-28 17:51 UTC, usageness commented on script.js
> +        }
[1]
for문을 통해서 배열 순회를 잘 해주셨어요!
자바스크립트에서 배열을 순회하는 또 다른 방법인 `forEach` 에 대해서도 알아볼까요?

- [forEach](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)


[2]
`x` 버튼을 두 번씩 눌러야 사라지는 버그가 있어요!
98번줄의 `return;`이 수상해보이는데 한 번 픽스해볼까요?

2023-01-28 17:51 UTC, usageness commented on script.js
> +    const scheduleDeleteButton = document.createElement('span');
스케줄을 지우는 역할을 하는 버튼인데, `<span>` 태그로 만들어주셨네요!
`<button>` 이나 `<input type="button">` 태그를 사용하시는건 어떨까요?

2023-01-28 17:51 UTC, usageness commented on script.js
> +        scheduleContainer.style.display = "none";
`style.display= 'none'` 으로 주게되면 화면 상에서는 사라지지만,
실제 요소는 그대로 남아있는 문제가 있어요.
id 값이 중복으로 생기기 때문에 다른 문제가 발생할 여지가 있는데, 한 번 수정해볼까요? 

![image](https://user-images.githubusercontent.com/28296575/215277506-8aa74000-2e12-4652-8656-d5ee65ac54c8.png)

2023-01-28 17:51 UTC, usageness commented on script.js
> +    return false;
검색 함수까지 만들어주시다니... 👏👏 
이럴때 사용하기 좋은 함수가 있죠! `Array.prototype.some()` 을 사용해볼까요?

- [Array.prototype.some()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

2023-01-28 17:51 UTC, usageness commented on script.js
> +        window.alert("이미 존재하는 스케줄입니다");
중복 확인 멋져요.. 👍

2023-01-28 17:51 UTC, usageness commented on style.css
> +    flex-direction: row;
`flex-direction: row` 는 따로 적어주지 않아도 되는 기본값입니다!

2023-01-31 07:05 UTC, ShinYoung-Kim commented on script.js
> +const NO_SCHEDULE_MESSAGE = 2;
아래 다른 리뷰를 토대로 해당 const들을 사용할 필요가 없어진 것 같아 위 const들은 삭제하였습니다!
+) 대신 다른 상수화를 시도할 때 문자열 상수화를 사용해 보았습니다. (1ea21fc6)

2023-01-31 07:06 UTC, ShinYoung-Kim commented on script.js
> +const schedulesContainer = document.getElementById("schedulesContainer");
불필요한 변수 선언들 제거했습니다

2023-01-31 07:07 UTC, ShinYoung-Kim commented on script.js
> +let scheduleArray = [];
599b649f 에서 변경했었는데 후에 코드 수정하던 중 array 요소 삭제를 하면서 const 대신 let으로 다시 변경하였습니다(b4f9ad01)

2023-01-31 07:10 UTC, ShinYoung-Kim commented on script.js
> +}
ba1d3e7b
hide/show 함수들을 살펴보니 +버튼이 보일때는 무조건 input container가 안 보이고, +버튼이 보이지 않을 때는 무조건 input container가 보이는 상황이길래 같이 쓰이는 코드끼리 묶어 새로운 함수로 만들어 보았습니다

2023-01-31 07:19 UTC, ShinYoung-Kim commented on script.js
> +        }
[1]
:질문: forEach는 배열의 index가 아닌 element를 가지고 순회하는 것으로 알고 있습니다. 위 코드를 forEach문으로 바꾸는 시도를 먼저 해보았는데 해당 element의 index를 알아야 splice를 사용할 수 있을 것 같아 수정할 수 없었습니다.
->java에서 배열 원소를 지울 때 index도 element도 parameter로 받을 수 있는 것처럼 js에서 splice가 element를 parameter로 받아 작용할 수 있는 건가요?
/ 현재는 filter를 이용하여 구현해둔 상태입니다. (b4f9ad01)
`scheduleDeleteButton.addEventListener("click", function () {
        scheduleArray = scheduleArray.filter((schedule) => schedule !== addedScheduleName);
        scheduleContainer.remove();
        changeContainerStyle();
    });`
:질문: filter를 사용해서 만들어진 새로운 array를 사용하게 되면 메모리를 낭비하는 코드가 된 건 아닐까요?

[2]
ec328ba3 수정했습니다!

2023-01-31 07:19 UTC, ShinYoung-Kim commented on script.js
> +    const scheduleDeleteButton = document.createElement('span');
ec328ba3
수정했습니다!

2023-01-31 07:20 UTC, ShinYoung-Kim commented on script.js
> +        scheduleContainer.style.display = "none";
remove를 이용하여 수정했습니다
369c5866

2023-01-31 07:21 UTC, ShinYoung-Kim commented on script.js
> +    return false;
eee190d2
수정했습니다!

2023-01-31 07:24 UTC, ShinYoung-Kim commented on style.css
> +    flex-direction: row;
789b56af
수정했습니다

2023-01-31 08:40 UTC, ShinYoung-Kim commented
**소감**
선배님께서 리뷰를 꼼꼼하게 봐주셔서 욕심도 생기고 재밌게 작업했습니다. 하면 할 수록 아직 부족한 점이 많은 게 느껴져서 열의도 많이 생기고 있는 것 같아요! 😄😄😄 

**질문**
[예약어]
최근 읽은 책에서 변수 네이밍에 대해 다뤄서 이번 제출에서 신경을 많이 써봤습니다. 그 중에서 
demandNewScheduleInputContainer 함수의 이름을 지을 때 고민이 있었는데요, 원래는 request/require를 접두어로 써서 함수 이름을 짓고 싶었는데 웹에서는 요청이라는 말을 사용하니까 혹시 이게 예약어가 되지는 않을지 걱정이 들었습니다.
-> request/require를 접두어로 쓰면 예약어를 쓰지 말라는 원칙을 어기는 걸까요? 
+) 타인이 코드를 볼 때 서버와 관련된 함수로 착각할 수 있어 지양하는 게 좋을까요?

[fixed 사용]
plus 버튼에서 텍스트가 버튼을 벗어나 생기는 문제를 해결하기 위해서 fixed를 사용하였는데 이런 경우 만약 페이지가 반응형이거나 요구 사항이 바뀌어서 버튼 텍스트 크기 등이 변경된다면 위치를 일일이 바꿔줘야 하지 않을까요? 선배님은 보통 어떤 상황에서 fixed를 쓰시는지 궁금합니다

[스타일이 있는 클래스]
피드백 주셨던 '대신 변경하고 싶은 스타일이 있는 클래스를 선언하고,
해당 클래스를 붙여주는 방식을 추천합니다!'를 해보고 싶어서 0f3eb1f1 처럼 구현해보았는데 의도하신 게 맞을지 여쭤보고 싶습니다.

**need help**
[중복되는 기능 합치기]
scheduleDeleteButton에서 (schedule) => schedule !== addedScheduleName를 따지고, addInput에서 (schedule) => schedule === addedScheduleName)를 따지는 기능을 하고 있는데 둘 중 하나의 함수를 만들어 다른 하나에는 결과 값에 not만 붙여주면 좋지 않을까 생각이 들었습니다 
-> 함수를 만들어도 some이나 filter의 안에 집어 넣으면 원하는 대로 동작되지 않습니다

[scroll]
![image](https://user-images.githubusercontent.com/83866983/215706160-1c15ac16-8380-4895-934c-1377b451a0d4.png)
사진처럼 scroll이 생기면 그 영역 위에 올라오는 것이 마음에 들지 않아 바꾸고 싶습니다. 
-> (faddc993) 스크롤이 존재하는지 하지 않는 지에 따라 li의 padding을 바꾸는 방법으로 코드를 작성했는데 이렇게 말고 실제 동작하는 영역을 줄이는 방법은 없을까요?

[content]
scheduleDeleteButton의 innerText까지도 css에서 미리 만들어서 제어하고 싶습니다. 인터넷에 찾아보니 content라는 게 있어서 적용을 해보았는데 (content: "x";) 텍스트가 보이지 않았고, ::after같은 가상 요소를 만들어서 content를 적용해 보았는데도 텍스트가 보이지 않았습니다. js에서 제어해주는 것이 최선일까요?

2023-01-31 09:24 UTC, usageness commented on script.js
> +    }
최상단에서 선언해주었던 isScheduleExist의 용도가 궁금했는데, 여기 있었네요~
이정도면 개인적으로는 굳이 변수로 바꾸지 않고 사용해도 무난했을것 같다는 생각은 들어요!
하지만 이대로도 좋습니다 👍

2023-01-31 09:24 UTC, usageness commented on script.js
> +        }
[1]
기본적으로 모든 순회는 length, 즉 인덱스를 기반으로 수행됩니다.
`forEach`의 용법을 보면, 아래처럼 현재 순회중인 인덱스도 확인할 수 있습니다.

```js
const newArr = ['a', 'b', 'c'];

newArr.forEach((e, i) => {
  console.log(`지금은 ${i}번째 순회이며, 값은 ${e}입니다.`);
});
```

splice는 인덱스만을 받기에, 값을 통해 인덱스를 먼저 찾아주셔야 할거에요 :)

filter를 이용하신 코드를 보면 새로운 array를 만들고, 기존의 array에 덮어씌우기 때문에
메모리 낭비는 걱정하지 않으셔도 괜찮습니다. (사용되지 않는 메모리 영역은 gc가 알아서 정리해줍니다!)

현재 브라우저 스펙은 개발자가 메모리를 신경쓰지 않아도 될 정도로 충분히 최적화가 잘 되어있으니
당장 메모리나 속도에 대한 효율성보다는 보기 좋고 유지보수하기 좋은 코드를 만드는데 중점을 두시는걸 추천합니다.

2023-01-31 10:21 UTC, usageness approved these changes
신영님, 고생하셨습니다!
리뷰를 반영하는 시간 동안 더 많은 고민이 담겼네요. 도움이 되셨기를 바라요 😊

유지보수 관점에서 현재의 설계가 최적인 상태인지 생각해보시고,
다음 요구사항도 잘 구현해주시길 바랄게요.

다음 미션 발표는 2월 2일 목요일입니다!

아래는 질문에 대한 답변입니다.

> [예약어]
최근 읽은 책에서 변수 네이밍에 대해 다뤄서 이번 제출에서 신경을 많이 써봤습니다. 그 중에서
demandNewScheduleInputContainer 함수의 이름을 지을 때 고민이 있었는데요, 원래는 request/require를 접두어로 써서 함수 이름을 짓고 싶었는데 웹에서는 요청이라는 말을 사용하니까 혹시 이게 예약어가 되지는 않을지 걱정이 들었습니다.
-> request/require를 접두어로 쓰면 예약어를 쓰지 말라는 원칙을 어기는 걸까요?
+) 타인이 코드를 볼 때 서버와 관련된 함수로 착각할 수 있어 지양하는 게 좋을까요?

우선 처음에 `demandNewScheduleInputContainer` 라는 함수 명을 보고 역할을 바로 유추하기엔 조금 어려움이 있었어요. 사용처를 가서 확인해보고 나서야 "스케줄을 입력하는 창을 보여주는" 역할인 것을 알게 되었습니다. 개발자들이 주로 사용하는 접두어 등을 찾아보시고, 잘 이용해보시면 이름을 지을때 조금 더 수월해지지 않을까요?

request, require 모두 실제로 존재하는 api긴 한데, 독립적으로 사용하는 경우는 없어서 크게 문제되는 경험은 없었습니다. 다만, 말씀하신것 처럼 request의 경우엔 서버로의 요청인 경우에 많이 사용하는 접두어다 보니 혼동이 있을 수는 있어 보입니다. 요청의 대상이 다른 곳으로 향하지 않는 이상 request는 사용해보진 않았던 것 같아요!


> [fixed 사용]
plus 버튼에서 텍스트가 버튼을 벗어나 생기는 문제를 해결하기 위해서 fixed를 사용하였는데 이런 경우 만약 페이지가 반응형이거나 요구 사항이 바뀌어서 버튼 텍스트 크기 등이 변경된다면 위치를 일일이 바꿔줘야 하지 않을까요? 선배님은 보통 어떤 상황에서 fixed를 쓰시는지 궁금합니다

개인적으로는 이번 미션의 `+` 버튼 같은경우, 텍스트로 사용하지 않는 편입니다.
이미지 파일을 불러와서 사용하거나, css로 그려주는 경우가 많았어요.

fixed는 버튼처럼 작은 요소들보다는, 큰 레이아웃을 잡을때 많이 사용했습니다.
저라면 이번 요구사항의 헤더 부분에 `position: fixed`를 적용했을것 같아요 :)

> [스타일이 있는 클래스]
피드백 주셨던 '대신 변경하고 싶은 스타일이 있는 클래스를 선언하고,
해당 클래스를 붙여주는 방식을 추천합니다!'를 해보고 싶어서 https://github.com/TeamCrazyPerformance/front-todolist/commit/0f3eb1f13bd28b73daa15b50d9689bd78aba960d 처럼 구현해보았는데 의도하신 게 맞을지 여쭤보고 싶습니다.

**맞습니다 😄👍👍**
지금은 하나뿐이라 태그 네임으로만 사용하셨지만,
나중에 같은 태그의 요소들이 많아지게 되면 단순히 태그 네임이 아닌
`.schedule-list` 같은 구체적인 이름으로 주시면 될거에요!


> [중복되는 기능 합치기]
scheduleDeleteButton에서 (schedule) => schedule !== addedScheduleName를 따지고, addInput에서 (schedule) => schedule === addedScheduleName)를 따지는 기능을 하고 있는데 둘 중 하나의 함수를 만들어 다른 하나에는 결과 값에 not만 붙여주면 좋지 않을까 생각이 들었습니다
-> 함수를 만들어도 some이나 filter의 안에 집어 넣으면 원하는 대로 동작되지 않습니다

좋은 아이디어라고 생각합니다~
some이나 filter 내부에서 동작하지 않는건 코드의 문제일 가능성이 있으니
시도해보신 코드도 함께 알려주시겠어요?

> [scroll]
사진처럼 scroll이 생기면 그 영역 위에 올라오는 것이 마음에 들지 않아 바꾸고 싶습니다.
-> (https://github.com/TeamCrazyPerformance/front-todolist/commit/faddc993efe0251e7895c73f0aaccc45d7c6be90) 스크롤이 존재하는지 하지 않는 지에 따라 li의 padding을 바꾸는 방법으로 코드를 작성했는데 이렇게 말고 실제 동작하는 영역을 줄이는 방법은 없을까요?

현재 `li` 태그에 적용되어있는 `width: 100vw` 를 `width: 100%` 로 바꾸시면 의도하신대로 동작하실 것 같습니다~
`vw`, `vh` 단위는 뷰포트를 기준으로 정해지기 때문에 스크롤바 영역까지 포함하게 됩니다.
이럴때 `%`를 이용하면 스크롤바 영역을 제외하고 차지하기 때문에
별도의 자바스크립트 없이도 스크롤에 가려지지 않을거에요!

> [content]
scheduleDeleteButton의 innerText까지도 css에서 미리 만들어서 제어하고 싶습니다. 인터넷에 찾아보니 content라는 게 있어서 적용을 해보았는데 (content: "x";) 텍스트가 보이지 않았고, ::after같은 가상 요소를 만들어서 content를 적용해 보았는데도 텍스트가 보이지 않았습니다. js에서 제어해주는 것이 최선일까요?

가상 요소는 말 그대로 가상의 요소입니다. 간단한 꾸미기라면 괜찮지만,
실제 dom에 영향을 주어야 하는 (추가적인 동작까지 필요한) 경우에는 권장하지 않습니다.
지금과 같은 버튼은 js를 통해 추가하거나 제거해주세요!

2023-01-31 10:21 UTC, merged