김신영 투두리스트 2차 미션 제출합니다.
TeamCrazyPerformance/front-todolist pull request #8
Opened 2023-02-08 06:43 UTC by ShinYoung-Kim

**배포 링크** : `https://shinyoung-kim.github.io/front-todolist/`

**질문**
❓’Buttons must have discernible text: Element has no title attribute’ 라는 메시지 뜨는데 지금처럼 이미지 버튼일 경우에는 무시해도 되나요?

❓local storage에 배열을 저장하고 getItem으로 불러오면 유사 배열로 불러와져서 some과 같은 함수를 사용할 수 없었습니다
→ Array()로 감싸서 바로 배열로 변경시키면 배열의 원소들이 변경되는 문제가 생겼고, 지금처럼 split을 사용하여 “,”를 기준으로 string을 배열로 바꿔주면 “~하고, ~하기”라는 이름의 todo list가 분리되는 문제가 발생합니다. 다른 해결 방법이 없을까요?

**소감**
아직 코드를 깔끔하게 짜는 데에 익숙하지가 않아 좀 아쉽습니다. 앞으로 열심히 배우면서 고쳐나가겠습니다! 
local storage는 처음 알게 되었는데 앞으로 유용하게 쓸 수 있을 것 같아요 😄

2023-02-08 09:34 UTC, usageness requested changes
안녕하세요, 신영님!
첫 제출 축하드립니다 👏👏 고생하셨어요!

2차 요구사항을 구현하시면서 프로그램의 전체적인 설계에 대해
다시 한 번 생각해보시는 계기가 되었으면 했는데,
신영님의 코드와 고민을 보니 잘 전해진 것 같아 다행입니다 😄

상세한 내용은 코멘트로 남겼으니 확인 부탁드리고,
수정할 부분이 있다면 수정해주세요!


아래는 질문에 대한 답변입니다!



> ❓’Buttons must have discernible text: Element has no title attribute’
> 라는 메시지 뜨는데 지금처럼 이미지 버튼일 경우에는 무시해도 되나요?

경고가 발생할때는 대부분의 경우 무시하지 않으시는게 좋습니다!
해당 경고는 버튼을 식별할만한 텍스트 데이터가 없어서 발생하는 경고입니다.

시각적으로 불편함이 없는 이용자에게는 이미지 버튼이 잘 와닿겠지만,
스크린 리더등의 보조 장비를 통해 화면을 보는 이용자에게는 
지금처럼 아무런 설명이 없는 이미지 버튼을 읽을 수 없다는 문제가 있습니다.

우리가 이미지 태그 `<img>` 를 사용할때 항상 `alt=""` 속성을 주어야 하는 이유도
이러한 문제점을 해결하기 위해 "읽을 수 있는" 데이터를 준다는 점에서 출발합니다.
(이미지가 로딩되지 않을때 대체 텍스트로도 표시되는 건 덤입니다!)

버튼에 title 속성을 추가해서 어떤 버튼인지 알려줄 수 있는 정보를 넣어주시고,
여유가 되신다면 **접근성**에 대해서도 한 번 찾아보시면 좋을 것 같아요 😊

> ❓local storage에 배열을 저장하고 getItem으로 불러오면 유사 배열로 불러와져서 some과 같은 함수를 사용할 수 없었습니다
> → Array()로 감싸서 바로 배열로 변경시키면 배열의 원소들이 변경되는 문제가 생겼고, 지금처럼 split을 사용하여 “,”를 기준으로 string을 배열로 바꿔주면 “~하고, ~하기”라는 이름의 todo list가 분리되는 문제가 발생합니다. 다른 해결 방법이 없을까요?

localStorage에는 string 데이터밖에 넣을 수 없기 때문에,
배열을 넣어버리면 간단히 해결되지만 그럴 수 없는 답답한 문제가 있습니다.
이렇게 문자열 기반의 데이터를 주고받을때 고안된 형식으로
[JSON](https://developer.mozilla.org/ko/docs/Learn/JavaScript/Objects/JSON) 이라는 형식이 있어요.
자바스크립트에서도 JSON이라는 내장 메서드를 이용해서
이 형식으로 자유롭게 변환할 수 있기 때문에 사용해보시길 추천드려요!

- [JSON.stringify()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)
- [JSON.parse()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)

2023-02-08 09:34 UTC, usageness commented on script.js
> +}
전체 모드를 편집(EDIT_MODE)과 보기(VIEW_MODE)모드 둘로 나누어서 관리하셨네요.
이럴 경우 한 가지 문제점이 있는데, 두 개 이상의 요소를 편집중일때
한 요소의 편집 완료를 누르게 되면 모든 요소의 편집이 종료되어요.
어떻게 관리하면 좋을지 한 번 생각해보시면 좋겠어요 :)

2023-02-08 09:34 UTC, usageness commented on script.js
> +    const editCompleteButton = document.createElement('button');
와우... 엄청난 길이의 함수네요! ㅋㅋㅋㅋ
혹시 지금의 코드가 복잡하고 깔끔하지 않아 보인다면,
지금처럼 길이가 상대적으로 긴 함수가 있는지 체크해보시고
분리해주는 방법을 사용하면 코드를 정리할 수 있어요.

만약 지금처럼 UI를 만들어주는 함수가 있다면,
파일 단위로 분리할 수 있는지도 한 번 확인해보시길 추천할게요!

2023-02-08 09:34 UTC, usageness commented on script.js
> +            window.alert("이미 존재하는 스케줄입니다");
이 부분은 동일한 이름으로 수정할 경우에 이미 존재하는 스케줄이라고 경고를 띄우기보다는,

- 처음 스케줄 내용과 동일한 경우
- (현재 스케줄이 아닌) 다른 스케줄 내용과 중복되는 경우

 두 가지로 나누면 더 좋을것 같아요!

2023-02-08 09:34 UTC, usageness commented on script.js
> +        let editedScheduleName = editInput.value;
값이 변경되지 않을때는 `const`를 사용해주시는걸 권장드립니다!

2023-02-08 09:34 UTC, usageness commented on script.js
> +    scheduleArray = localStorage.length === 0? [] : localStorage.getItem("scheduleArray").split(",");
`localStorage` 에는 다양한 데이터들이 들어갈 수 있어서,
`length가 0이 아니다` 라는 조건만으로는 `scheduleArray`가 있다고 확신할 수 없어요!
특정한 값이 있는지 지정해서 확인해주는걸 추천합니다.

```diff
- scheduleArray = localStorage.length === 0? [] : localStorage.getItem("scheduleArray").split(",");
+ const storedSchedule = localStorage.getItem("scheduleArray");
+ scheduleArray = storedSchedule === null ? [] : storedSchedule.split(",");
```

2023-02-08 09:34 UTC, usageness commented on script.js
>      plusButton.style.display = "none";
element의 inline 스타일을 직접적으로 건드리는것 보다는,
해당 스타일을 선언한 css 클래스를 달아주는 방식을 사용해보시는건 어떨까요?

2023-02-08 09:34 UTC, usageness commented on script.js
> +    scheduleArray.reverse();
😄👍👍

2023-02-08 09:34 UTC, usageness commented on style.css
> +    padding: 9px 12px 10px 11px;
디테일 대단해요... 😮

2023-02-19 09:34 UTC, ShinYoung-Kim commented on script.js
> +}
별도의 함수로 분리하였고 해당 함수 이후 페이지를 다시 그리던 작업을 제거해서 해결했습니다

2023-02-19 09:35 UTC, ShinYoung-Kim commented on script.js
> +    const editCompleteButton = document.createElement('button');
367688d0
수정했습니다!

2023-02-19 09:35 UTC, ShinYoung-Kim commented on script.js
> +            window.alert("이미 존재하는 스케줄입니다");
43d8d34
수정했습니다!

2023-02-19 09:36 UTC, ShinYoung-Kim commented on script.js
> +        let editedScheduleName = editInput.value;
161a84ef
수정했습니다!

2023-02-19 09:37 UTC, ShinYoung-Kim commented on script.js
> +    scheduleArray = localStorage.length === 0? [] : localStorage.getItem("scheduleArray").split(",");
b88f541a
변경했습니다

2023-02-19 09:37 UTC, ShinYoung-Kim commented on script.js
>      plusButton.style.display = "none";
b12d49ac
변경했습니다

2023-02-19 09:38 UTC, ShinYoung-Kim commented
우연히 template라는 태그를 알게 되어 이 태그를 써보고 싶다는 고집을 부리다가 업로드가 늦어졌습니다(ㅠㅠ) 앞으로는 빠르게 업로드 할 수 있도록 하겠습니다!

[질문]
❓ schedule edit mode를 view mode로 바꿀 때 getScheduleViewMode라는 함수를 사용하고 있습니다. 어떤 상황에서는 매개변수가 하나만 필요하고 어떤 상황에서는 매개변수가 2개가 필요한데 자바스크립트에서는 메서드 오버로딩을 지원하지 않는다고 하여 지금처럼 코드를 작성하였습니다. 이런 경우 매개변수에 따라 아예 다른 메서드를 만들어주는 것이 나을까요?

2023-02-22 13:25 UTC, usageness approved these changes
리뷰가 늦어져서 죄송합니다!
고생 많으셨어요 😄👍👍

변경 내용 확인했고, 이전보다 코드가 정리된 모습이 눈에 띄어서 좋네요 :)
다음에는 파일 하나가 너무 길어지지 않게 파일 단위로 분리를 시도해보시면 좋을것 같고,
메서드들의 이름에 대해서도 깊게 고민해보시기를 추천해요!

이 이름이 적절한지에 대해서 고민하기 시작하면,
이름에 대한 고민이 자연스럽게 좋은 설계에 대한 고민으로 발전할 여지가 많아요.
예를 들어 함수의 기능을 명확히 설명하는 이름이 팍 떠오르지 않았다면
그 자체로 함수가 너무 많은 일을 하고 있지는 않은지 확인할 수 있는 신호가 됩니다.

질문으로 남겨주신 내용도 위 내용의 연장선상이라고 생각이 들어요.

> ❓ schedule edit mode를 view mode로 바꿀 때 getScheduleViewMode라는 함수를 사용하고 있습니다. 어떤 상황에서는 매개변수가 하나만 필요하고 어떤 상황에서는 매개변수가 2개가 필요한데 자바스크립트에서는 메서드 오버로딩을 지원하지 않는다고 하여 지금처럼 코드를 작성하였습니다. 이런 경우 매개변수에 따라 아예 다른 메서드를 만들어주는 것이 나을까요?

지금 이 `getScheduleViewMode` 함수의 경우도 제가 보기엔 너무 많은 일들을 해서
매개변수를 어떻게 주어야 할지에 대한 고민으로 흘러가게 된 느낌이 강해요.

한번에 수정(또는 취소)도 해야하고, input 태그에서 일반 태그로 바꿔주기도 해야하고...
만약 이 모든 과정이 따로 이루어진다면 오버로딩을 고민할 필요도 없었을것 같아요 :)
결론적으로는 분기가 이루어지는 상황에서, 서로 다른 함수가 들어가는게 맞다고 보이네요!

---

특히나 길고 어려웠던 이번 미션 수행하시느라 고생 많으셨고,
이제 마지막 미션을 향해서 달려봅시다.

고생하셨습니다!

2023-02-22 13:26 UTC, merged